### ISSUE TITLE
Break in Google Map Service on Web Broswer

### ISSUE THREAD

**Issue by limingho456** [hkabdtunnel/hkabdtunnel#6]
Looks like the integration of google map service is out-to-date.

![image](https://user-images.githubusercontent.com/32219985/201532255-1a4a27cd-81af-432a-a29c-0a5aefed41d2.png)

**Comment by cityugreensleeves** [comment]
Encounter same issue on my side but looks like the site haven't been maintained for a while.

As a alternatives, you can get traffic from google map in your personal device
https://support.google.com/maps/answer/6337401?hl=en

**Comment by limingho456** [comment]
Thanks and close the issue.
